package gov.nasa.pds.harvest.crawler;

import java.io.File;

import javax.xml.parsers.DocumentBuilderFactory;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.w3c.dom.Document;

import gov.nasa.pds.harvest.cfg.model.Configuration;
import gov.nasa.pds.harvest.cfg.model.FileRefCfg;
import gov.nasa.pds.harvest.meta.AutogenExtractor;
import gov.nasa.pds.harvest.meta.BasicMetadataExtractor;
import gov.nasa.pds.harvest.meta.FileData;
import gov.nasa.pds.harvest.meta.FileDataExtractor;
import gov.nasa.pds.harvest.meta.InternalReferenceExtractor;
import gov.nasa.pds.harvest.meta.Metadata;
import gov.nasa.pds.harvest.meta.XPathExtractor;
import gov.nasa.pds.harvest.util.solr.SolrDocWriter;
import gov.nasa.pds.harvest.util.xml.XmlDomUtils;


public class MetadataProcessor
{
    private Logger LOG;

    private Configuration config;
    private SolrDocWriter writer;
    
    private BasicMetadataExtractor basicExtractor;
    private InternalReferenceExtractor refExtractor;
    private AutogenExtractor autogenExtractor;
    private FileDataExtractor fileDataExtractor;
    
    
    public MetadataProcessor(File outDir, Configuration config) throws Exception
    {
        LOG = LogManager.getLogger(getClass());
        
        writer = new SolrDocWriter(outDir);
        
        basicExtractor = new BasicMetadataExtractor();
        refExtractor = new InternalReferenceExtractor(config.internalRefs);
        autogenExtractor = new AutogenExtractor();
        fileDataExtractor = new FileDataExtractor(config);
        
        this.config = config;
    }

    
    public void process(File file, Counter counter) throws Exception
    {
        LOG.info("Processing file " + file.toURI().getPath());

        // Parse XML, ignore namespaces. 
        // Basic and XPath extractor are much easier to use without namespaces.
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        dbf.setNamespaceAware(false);
        Document doc = XmlDomUtils.readXml(dbf, file);
        String rootElement = doc.getDocumentElement().getNodeName();
        
        // Extract basic metadata
        Metadata meta = basicExtractor.extract(doc);
        validate(meta, file);
        
        // Internal references
        meta.intRefs = refExtractor.extract(doc);
        
        // Extract fields by XPath
        XPathExtractor.extract(doc, meta.fields);

        // Extract fields autogenerated from data dictionary
        if(config.autoGenFields)
        {
            autogenExtractor.extract(file, meta.fields);
        }

        // Set file reference
        setFileRef(meta, file);

        // Extract file data
        FileData fd = fileDataExtractor.extract(file);
        
        writer.write(fd, meta);
        
        counter.prodCounters.inc(rootElement);
    }
    
    
    public void close() throws Exception
    {
        writer.close();
    }
    
    
    private void validate(Metadata meta, File file) throws Exception
    {
        if(meta.lid == null || meta.lid.isEmpty())
        {
            throw new Exception("Missing logical identifier: " + file.toURI().getPath());
        }

        if(meta.vid == null || meta.vid.isEmpty())
        {
            throw new Exception("Missing version id: " + file.toURI().getPath());
        }
    }

    
    private void setFileRef(Metadata meta, File file)
    {
        if(config.fileRef == null) return;
        String filePath = file.toURI().getPath();
        
        if(config.fileRef.rules != null)
        {
            for(FileRefCfg.ReplaceRule rule: config.fileRef.rules)
            {
                if(rule.prefix == null || rule.replacement == null) continue;
                
                if(filePath.startsWith(rule.prefix))
                {
                    filePath = rule.replacement + filePath.substring(rule.prefix.length());
                    break;
                }
            }
        }
        
        meta.fileRef = filePath;
    }
    
}
