//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 08:05:55 PM PDT 
//


package gov.nasa.pds.harvest.search.policy;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nasa.pds.harvest.search.policy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FileTypeMap_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "fileTypeMap");
    private final static QName _TitleContents_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "titleContents");
    private final static QName _Candidates_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "candidates");
    private final static QName _BaseUrl_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "baseUrl");
    private final static QName _StaticMetadata_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "staticMetadata");
    private final static QName _XPath_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "xPath");
    private final static QName _Name_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "name");
    private final static QName _Namespace_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "namespace");
    private final static QName _ModelValue_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "modelValue");
    private final static QName _Offset_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "offset");
    private final static QName _Manifest_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "manifest");
    private final static QName _StorageIngestion_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "storageIngestion");
    private final static QName _Include_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "include");
    private final static QName _FileTypes_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "fileTypes");
    private final static QName _Pds3ProductMetadata_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "pds3ProductMetadata");
    private final static QName _Collections_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "collections");
    private final static QName _AncillaryMetadata_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "ancillaryMetadata");
    private final static QName _ServerUrl_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "serverUrl");
    private final static QName _ReferenceTypeMap_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "referenceTypeMap");
    private final static QName _Path_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "path");
    private final static QName _File_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "file");
    private final static QName _ProductMetadata_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "productMetadata");
    private final static QName _Value_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "value");
    private final static QName _LidContents_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "lidContents");
    private final static QName _Directories_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "directories");
    private final static QName _Exclude_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "exclude");
    private final static QName _RegistryPackage_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "registryPackage");
    private final static QName _References_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "references");
    private final static QName _DataTransferType_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "dataTransferType");
    private final static QName _AccessUrl_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "accessUrl");
    private final static QName _AccessUrls_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "accessUrls");
    private final static QName _Checksums_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "checksums");
    private final static QName _FileFilter_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "fileFilter");
    private final static QName _DirectoryFilter_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "directoryFilter");
    private final static QName _ElementName_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "elementName");
    private final static QName _IncludePaths_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "includePaths");
    private final static QName _Description_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "description");
    private final static QName _Slot_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "slot");
    private final static QName _Pds3Directories_QNAME = new QName("https://pds.nasa.gov/software/pds4/harvest/v1", "pds3Directories");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nasa.pds.harvest.search.policy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Checksums }
     * 
     */
    public Checksums createChecksums() {
        return new Checksums();
    }

    /**
     * Create an instance of {@link FileFilter }
     * 
     */
    public FileFilter createFileFilter() {
        return new FileFilter();
    }

    /**
     * Create an instance of {@link DirectoryFilter }
     * 
     */
    public DirectoryFilter createDirectoryFilter() {
        return new DirectoryFilter();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link AccessUrl }
     * 
     */
    public AccessUrl createAccessUrl() {
        return new AccessUrl();
    }

    /**
     * Create an instance of {@link AccessUrls }
     * 
     */
    public AccessUrls createAccessUrls() {
        return new AccessUrls();
    }

    /**
     * Create an instance of {@link IncludePath }
     * 
     */
    public IncludePath createIncludePath() {
        return new IncludePath();
    }

    /**
     * Create an instance of {@link Slot }
     * 
     */
    public Slot createSlot() {
        return new Slot();
    }

    /**
     * Create an instance of {@link Pds3Directory }
     * 
     */
    public Pds3Directory createPds3Directory() {
        return new Pds3Directory();
    }

    /**
     * Create an instance of {@link ElementName }
     * 
     */
    public ElementName createElementName() {
        return new ElementName();
    }

    /**
     * Create an instance of {@link ReferenceTypeMap }
     * 
     */
    public ReferenceTypeMap createReferenceTypeMap() {
        return new ReferenceTypeMap();
    }

    /**
     * Create an instance of {@link Pds4ProductMetadata }
     * 
     */
    public Pds4ProductMetadata createPds4ProductMetadata() {
        return new Pds4ProductMetadata();
    }

    /**
     * Create an instance of {@link Collection }
     * 
     */
    public Collection createCollection() {
        return new Collection();
    }

    /**
     * Create an instance of {@link AncillaryMetadata }
     * 
     */
    public AncillaryMetadata createAncillaryMetadata() {
        return new AncillaryMetadata();
    }

    /**
     * Create an instance of {@link Directory }
     * 
     */
    public Directory createDirectory() {
        return new Directory();
    }

    /**
     * Create an instance of {@link RegistryPackage }
     * 
     */
    public RegistryPackage createRegistryPackage() {
        return new RegistryPackage();
    }

    /**
     * Create an instance of {@link LidContents }
     * 
     */
    public LidContents createLidContents() {
        return new LidContents();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link StorageIngestion }
     * 
     */
    public StorageIngestion createStorageIngestion() {
        return new StorageIngestion();
    }

    /**
     * Create an instance of {@link Candidate }
     * 
     */
    public Candidate createCandidate() {
        return new Candidate();
    }

    /**
     * Create an instance of {@link FileTypes }
     * 
     */
    public FileTypes createFileTypes() {
        return new FileTypes();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link Pds3ProductMetadata }
     * 
     */
    public Pds3ProductMetadata createPds3ProductMetadata() {
        return new Pds3ProductMetadata();
    }

    /**
     * Create an instance of {@link TitleContents }
     * 
     */
    public TitleContents createTitleContents() {
        return new TitleContents();
    }

    /**
     * Create an instance of {@link StaticMetadata }
     * 
     */
    public StaticMetadata createStaticMetadata() {
        return new StaticMetadata();
    }

    /**
     * Create an instance of {@link FileTypeMap }
     * 
     */
    public FileTypeMap createFileTypeMap() {
        return new FileTypeMap();
    }

    /**
     * Create an instance of {@link Namespace }
     * 
     */
    public Namespace createNamespace() {
        return new Namespace();
    }

    /**
     * Create an instance of {@link XPath }
     * 
     */
    public XPath createXPath() {
        return new XPath();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileTypeMap }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "fileTypeMap")
    public JAXBElement<FileTypeMap> createFileTypeMap(FileTypeMap value) {
        return new JAXBElement<FileTypeMap>(_FileTypeMap_QNAME, FileTypeMap.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleContents }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "titleContents")
    public JAXBElement<TitleContents> createTitleContents(TitleContents value) {
        return new JAXBElement<TitleContents>(_TitleContents_QNAME, TitleContents.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Candidate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "candidates")
    public JAXBElement<Candidate> createCandidates(Candidate value) {
        return new JAXBElement<Candidate>(_Candidates_QNAME, Candidate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "baseUrl")
    public JAXBElement<String> createBaseUrl(String value) {
        return new JAXBElement<String>(_BaseUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StaticMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "staticMetadata")
    public JAXBElement<StaticMetadata> createStaticMetadata(StaticMetadata value) {
        return new JAXBElement<StaticMetadata>(_StaticMetadata_QNAME, StaticMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XPath }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "xPath")
    public JAXBElement<XPath> createXPath(XPath value) {
        return new JAXBElement<XPath>(_XPath_QNAME, XPath.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Namespace }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "namespace")
    public JAXBElement<Namespace> createNamespace(Namespace value) {
        return new JAXBElement<Namespace>(_Namespace_QNAME, Namespace.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "modelValue")
    public JAXBElement<String> createModelValue(String value) {
        return new JAXBElement<String>(_ModelValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "offset")
    public JAXBElement<String> createOffset(String value) {
        return new JAXBElement<String>(_Offset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Manifest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "manifest")
    public JAXBElement<Manifest> createManifest(Manifest value) {
        return new JAXBElement<Manifest>(_Manifest_QNAME, Manifest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StorageIngestion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "storageIngestion")
    public JAXBElement<StorageIngestion> createStorageIngestion(StorageIngestion value) {
        return new JAXBElement<StorageIngestion>(_StorageIngestion_QNAME, StorageIngestion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "include")
    public JAXBElement<String> createInclude(String value) {
        return new JAXBElement<String>(_Include_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "fileTypes")
    public JAXBElement<FileTypes> createFileTypes(FileTypes value) {
        return new JAXBElement<FileTypes>(_FileTypes_QNAME, FileTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pds3ProductMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "pds3ProductMetadata")
    public JAXBElement<Pds3ProductMetadata> createPds3ProductMetadata(Pds3ProductMetadata value) {
        return new JAXBElement<Pds3ProductMetadata>(_Pds3ProductMetadata_QNAME, Pds3ProductMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Collection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "collections")
    public JAXBElement<Collection> createCollections(Collection value) {
        return new JAXBElement<Collection>(_Collections_QNAME, Collection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AncillaryMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "ancillaryMetadata")
    public JAXBElement<AncillaryMetadata> createAncillaryMetadata(AncillaryMetadata value) {
        return new JAXBElement<AncillaryMetadata>(_AncillaryMetadata_QNAME, AncillaryMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "serverUrl")
    public JAXBElement<String> createServerUrl(String value) {
        return new JAXBElement<String>(_ServerUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceTypeMap }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "referenceTypeMap")
    public JAXBElement<ReferenceTypeMap> createReferenceTypeMap(ReferenceTypeMap value) {
        return new JAXBElement<ReferenceTypeMap>(_ReferenceTypeMap_QNAME, ReferenceTypeMap.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "path")
    public JAXBElement<String> createPath(String value) {
        return new JAXBElement<String>(_Path_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "file")
    public JAXBElement<String> createFile(String value) {
        return new JAXBElement<String>(_File_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pds4ProductMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "productMetadata")
    public JAXBElement<Pds4ProductMetadata> createProductMetadata(Pds4ProductMetadata value) {
        return new JAXBElement<Pds4ProductMetadata>(_ProductMetadata_QNAME, Pds4ProductMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LidContents }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "lidContents")
    public JAXBElement<LidContents> createLidContents(LidContents value) {
        return new JAXBElement<LidContents>(_LidContents_QNAME, LidContents.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Directory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "directories")
    public JAXBElement<Directory> createDirectories(Directory value) {
        return new JAXBElement<Directory>(_Directories_QNAME, Directory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "exclude")
    public JAXBElement<String> createExclude(String value) {
        return new JAXBElement<String>(_Exclude_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryPackage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "registryPackage")
    public JAXBElement<RegistryPackage> createRegistryPackage(RegistryPackage value) {
        return new JAXBElement<RegistryPackage>(_RegistryPackage_QNAME, RegistryPackage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link References }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "references")
    public JAXBElement<References> createReferences(References value) {
        return new JAXBElement<References>(_References_QNAME, References.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "dataTransferType")
    public JAXBElement<String> createDataTransferType(String value) {
        return new JAXBElement<String>(_DataTransferType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessUrl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "accessUrl")
    public JAXBElement<AccessUrl> createAccessUrl(AccessUrl value) {
        return new JAXBElement<AccessUrl>(_AccessUrl_QNAME, AccessUrl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccessUrls }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "accessUrls")
    public JAXBElement<AccessUrls> createAccessUrls(AccessUrls value) {
        return new JAXBElement<AccessUrls>(_AccessUrls_QNAME, AccessUrls.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Checksums }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "checksums")
    public JAXBElement<Checksums> createChecksums(Checksums value) {
        return new JAXBElement<Checksums>(_Checksums_QNAME, Checksums.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "fileFilter")
    public JAXBElement<FileFilter> createFileFilter(FileFilter value) {
        return new JAXBElement<FileFilter>(_FileFilter_QNAME, FileFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DirectoryFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "directoryFilter")
    public JAXBElement<DirectoryFilter> createDirectoryFilter(DirectoryFilter value) {
        return new JAXBElement<DirectoryFilter>(_DirectoryFilter_QNAME, DirectoryFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "elementName")
    public JAXBElement<ElementName> createElementName(ElementName value) {
        return new JAXBElement<ElementName>(_ElementName_QNAME, ElementName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncludePath }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "includePaths")
    public JAXBElement<IncludePath> createIncludePaths(IncludePath value) {
        return new JAXBElement<IncludePath>(_IncludePaths_QNAME, IncludePath.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Slot }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "slot")
    public JAXBElement<Slot> createSlot(Slot value) {
        return new JAXBElement<Slot>(_Slot_QNAME, Slot.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pds3Directory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", name = "pds3Directories")
    public JAXBElement<Pds3Directory> createPds3Directories(Pds3Directory value) {
        return new JAXBElement<Pds3Directory>(_Pds3Directories_QNAME, Pds3Directory.class, null, value);
    }

}
