//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 08:05:55 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://pds.nasa.gov/software/pds4/harvest/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nasa.pds.harvest.search.policy;
