//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 08:05:55 PM PDT 
//


package gov.nasa.pds.harvest.search.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pds3ProductMetadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pds3ProductMetadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}lidContents"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}titleContents" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}staticMetadata" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}ancillaryMetadata" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}includePaths" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute ref="{https://pds.nasa.gov/software/pds4/harvest/v1}objectType"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pds3ProductMetadata", propOrder = {

})
public class Pds3ProductMetadata {

    @XmlElement(required = true)
    protected LidContents lidContents;
    protected TitleContents titleContents;
    protected StaticMetadata staticMetadata;
    protected AncillaryMetadata ancillaryMetadata;
    protected IncludePath includePaths;
    @XmlAttribute(name = "objectType", namespace = "https://pds.nasa.gov/software/pds4/harvest/v1")
    protected String objectType;

    /**
     * Gets the value of the lidContents property.
     * 
     * @return
     *     possible object is
     *     {@link LidContents }
     *     
     */
    public LidContents getLidContents() {
        return lidContents;
    }

    /**
     * Sets the value of the lidContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link LidContents }
     *     
     */
    public void setLidContents(LidContents value) {
        this.lidContents = value;
    }

    /**
     * Gets the value of the titleContents property.
     * 
     * @return
     *     possible object is
     *     {@link TitleContents }
     *     
     */
    public TitleContents getTitleContents() {
        return titleContents;
    }

    /**
     * Sets the value of the titleContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleContents }
     *     
     */
    public void setTitleContents(TitleContents value) {
        this.titleContents = value;
    }

    /**
     * Gets the value of the staticMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link StaticMetadata }
     *     
     */
    public StaticMetadata getStaticMetadata() {
        return staticMetadata;
    }

    /**
     * Sets the value of the staticMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticMetadata }
     *     
     */
    public void setStaticMetadata(StaticMetadata value) {
        this.staticMetadata = value;
    }

    /**
     * Gets the value of the ancillaryMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link AncillaryMetadata }
     *     
     */
    public AncillaryMetadata getAncillaryMetadata() {
        return ancillaryMetadata;
    }

    /**
     * Sets the value of the ancillaryMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link AncillaryMetadata }
     *     
     */
    public void setAncillaryMetadata(AncillaryMetadata value) {
        this.ancillaryMetadata = value;
    }

    /**
     * Gets the value of the includePaths property.
     * 
     * @return
     *     possible object is
     *     {@link IncludePath }
     *     
     */
    public IncludePath getIncludePaths() {
        return includePaths;
    }

    /**
     * Sets the value of the includePaths property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludePath }
     *     
     */
    public void setIncludePaths(IncludePath value) {
        this.includePaths = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectType(String value) {
        this.objectType = value;
    }

}
