//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 08:05:55 PM PDT 
//


package gov.nasa.pds.harvest.search.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}registryPackage" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}collections" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}directories" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}pds3Directories" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}storageIngestion" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}accessUrls" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}checksums" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}candidates"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}references" minOccurs="0"/>
 *         &lt;element ref="{https://pds.nasa.gov/software/pds4/harvest/v1}fileTypes" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "policy")
public class Policy {

    protected RegistryPackage registryPackage;
    protected Collection collections;
    protected Directory directories;
    protected Pds3Directory pds3Directories;
    protected StorageIngestion storageIngestion;
    protected AccessUrls accessUrls;
    protected Checksums checksums;
    @XmlElement(required = true)
    protected Candidate candidates;
    protected References references;
    protected FileTypes fileTypes;

    public Policy() {
        registryPackage = new RegistryPackage();
        directories = new Directory();
        pds3Directories = new Pds3Directory();
        collections = new Collection();
        storageIngestion = null;
        accessUrls = new AccessUrls();
        references = new References();
        checksums = new Checksums();
        fileTypes = new FileTypes();
      }
    
    /**
     * Gets the value of the registryPackage property.
     * 
     * @return
     *     possible object is
     *     {@link RegistryPackage }
     *     
     */
    public RegistryPackage getRegistryPackage() {
        return registryPackage;
    }

    /**
     * Sets the value of the registryPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistryPackage }
     *     
     */
    public void setRegistryPackage(RegistryPackage value) {
        this.registryPackage = value;
    }

    /**
     * Gets the value of the collections property.
     * 
     * @return
     *     possible object is
     *     {@link Collection }
     *     
     */
    public Collection getCollections() {
        return collections;
    }

    /**
     * Sets the value of the collections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Collection }
     *     
     */
    public void setCollections(Collection value) {
        this.collections = value;
    }

    /**
     * Gets the value of the directories property.
     * 
     * @return
     *     possible object is
     *     {@link Directory }
     *     
     */
    public Directory getDirectories() {
        return directories;
    }

    /**
     * Sets the value of the directories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Directory }
     *     
     */
    public void setDirectories(Directory value) {
        this.directories = value;
    }

    /**
     * Gets the value of the pds3Directories property.
     * 
     * @return
     *     possible object is
     *     {@link Pds3Directory }
     *     
     */
    public Pds3Directory getPds3Directories() {
        return pds3Directories;
    }

    /**
     * Sets the value of the pds3Directories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pds3Directory }
     *     
     */
    public void setPds3Directories(Pds3Directory value) {
        this.pds3Directories = value;
    }

    /**
     * Gets the value of the storageIngestion property.
     * 
     * @return
     *     possible object is
     *     {@link StorageIngestion }
     *     
     */
    public StorageIngestion getStorageIngestion() {
        return storageIngestion;
    }

    /**
     * Sets the value of the storageIngestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageIngestion }
     *     
     */
    public void setStorageIngestion(StorageIngestion value) {
        this.storageIngestion = value;
    }

    /**
     * Gets the value of the accessUrls property.
     * 
     * @return
     *     possible object is
     *     {@link AccessUrls }
     *     
     */
    public AccessUrls getAccessUrls() {
        return accessUrls;
    }

    /**
     * Sets the value of the accessUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessUrls }
     *     
     */
    public void setAccessUrls(AccessUrls value) {
        this.accessUrls = value;
    }

    /**
     * Gets the value of the checksums property.
     * 
     * @return
     *     possible object is
     *     {@link Checksums }
     *     
     */
    public Checksums getChecksums() {
        return checksums;
    }

    /**
     * Sets the value of the checksums property.
     * 
     * @param value
     *     allowed object is
     *     {@link Checksums }
     *     
     */
    public void setChecksums(Checksums value) {
        this.checksums = value;
    }

    /**
     * Gets the value of the candidates property.
     * 
     * @return
     *     possible object is
     *     {@link Candidate }
     *     
     */
    public Candidate getCandidates() {
        return candidates;
    }

    /**
     * Sets the value of the candidates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Candidate }
     *     
     */
    public void setCandidates(Candidate value) {
        this.candidates = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link References }
     *     
     */
    public References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link References }
     *     
     */
    public void setReferences(References value) {
        this.references = value;
    }

    /**
     * Gets the value of the fileTypes property.
     * 
     * @return
     *     possible object is
     *     {@link FileTypes }
     *     
     */
    public FileTypes getFileTypes() {
        return fileTypes;
    }

    /**
     * Sets the value of the fileTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileTypes }
     *     
     */
    public void setFileTypes(FileTypes value) {
        this.fileTypes = value;
    }

}
