//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nasa.pds.harvest.cfg;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for algorithm_enum</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="algorithm_enum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     <enumeration value="none"/>
 *     <enumeration value="bzip"/>
 *     <enumeration value="fpack"/>
 *     <enumeration value="gzip"/>
 *     <enumeration value="zip"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "algorithm_enum")
@XmlEnum
public enum AlgorithmEnum {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("bzip")
    BZIP("bzip"),
    @XmlEnumValue("fpack")
    FPACK("fpack"),
    @XmlEnumValue("gzip")
    GZIP("gzip"),
    @XmlEnumValue("zip")
    ZIP("zip");
    private final String value;

    AlgorithmEnum(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static AlgorithmEnum fromValue(String v) {
        for (AlgorithmEnum c: AlgorithmEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
