//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.14 at 10:43:09 PM UTC 
//


package gov.nasa.pds.harvest.cfg;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for algorithm_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="algorithm_enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString"&gt;
 *     &lt;enumeration value="bzip"/&gt;
 *     &lt;enumeration value="fpack"/&gt;
 *     &lt;enumeration value="gzip"/&gt;
 *     &lt;enumeration value="zip"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "algorithm_enum")
@XmlEnum
public enum AlgorithmEnum {

    @XmlEnumValue("bzip")
    BZIP("bzip"),
    @XmlEnumValue("fpack")
    FPACK("fpack"),
    @XmlEnumValue("gzip")
    GZIP("gzip"),
    @XmlEnumValue("zip")
    ZIP("zip");
    private final String value;

    AlgorithmEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AlgorithmEnum fromValue(String v) {
        for (AlgorithmEnum c: AlgorithmEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
