//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.14 at 10:43:09 PM UTC 
//


package gov.nasa.pds.harvest.cfg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *         The collection's LID or LIDVID.
 * 
 *         DEV notes:
 * 
 *         Unfortunately, cannot define mutually exclusive attributes
 *         without schematron and trying to avoid schematron.
 * 
 *         It may be better to ditch either lid or lidvid then if :: is found
 *         treat it as lidvid otherwise lid. Doing that would allow for the
 *         attribute lid as required but accept lidvids.
 *       
 * 
 * <p>Java class for collection_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="collection_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="lid" type="{http://www.w3.org/2001/XMLSchema}normalizedString" default="" /&gt;
 *       &lt;attribute name="lidvid" type="{http://www.w3.org/2001/XMLSchema}normalizedString" default="" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "collection_type")
public class CollectionType {

    @XmlAttribute(name = "lid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String lid;
    @XmlAttribute(name = "lidvid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String lidvid;

    /**
     * Gets the value of the lid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLid() {
        if (lid == null) {
            return "";
        } else {
            return lid;
        }
    }

    /**
     * Sets the value of the lid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLid(String value) {
        this.lid = value;
    }

    /**
     * Gets the value of the lidvid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLidvid() {
        if (lidvid == null) {
            return "";
        } else {
            return lidvid;
        }
    }

    /**
     * Sets the value of the lidvid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLidvid(String value) {
        this.lidvid = value;
    }

}
