//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.14 at 10:43:09 PM UTC 
//


package gov.nasa.pds.harvest.cfg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         These are the basic options for the harvest configuration file.
 * 
 * 
 *         autogenFields: should not be used except in development testing
 *         load: tells where and how to harvest PDS4 labels
 *         fileInfo: option allowing filename prefixes to be replaced
 *         nodeName: the PDS node that this harvest run applies to
 *         productFilter: should not be used except in development testing
 *         registry: define the server harvest should use
 *         xpathMaps: allow constraints in the PDS4 label to control harvesting
 *       
 * 
 * <p>Java class for harvest_configuration_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="harvest_configuration_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="autogenFields" type="{}autogen_fields_type" minOccurs="0"/&gt;
 *         &lt;element name="load" type="{}load_type"/&gt;
 *         &lt;element name="fileInfo" type="{}file_info_type" minOccurs="0"/&gt;
 *         &lt;element name="productFilter" type="{}filter_type" minOccurs="0"/&gt;
 *         &lt;element name="references" type="{}references_type" minOccurs="0"/&gt;
 *         &lt;element name="registry" type="{}registry_type"/&gt;
 *         &lt;element name="xpathMaps" type="{}xpath_maps_type" minOccurs="0"/&gt;
 *         &lt;element name="compiled" type="{}compiled_type" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "harvest_configuration_type", propOrder = {

})
@XmlSeeAlso({
    Harvest.class
})
public class HarvestConfigurationType {

    protected AutogenFieldsType autogenFields;
    @XmlElement(required = true)
    protected LoadType load;
    protected FileInfoType fileInfo;
    protected FilterType productFilter;
    protected ReferencesType references;
    @XmlElement(required = true)
    protected RegistryType registry;
    protected XpathMapsType xpathMaps;
    protected CompiledType compiled;

    /**
     * Gets the value of the autogenFields property.
     * 
     * @return
     *     possible object is
     *     {@link AutogenFieldsType }
     *     
     */
    public AutogenFieldsType getAutogenFields() {
        return autogenFields;
    }

    /**
     * Sets the value of the autogenFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutogenFieldsType }
     *     
     */
    public void setAutogenFields(AutogenFieldsType value) {
        this.autogenFields = value;
    }

    /**
     * Gets the value of the load property.
     * 
     * @return
     *     possible object is
     *     {@link LoadType }
     *     
     */
    public LoadType getLoad() {
        return load;
    }

    /**
     * Sets the value of the load property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadType }
     *     
     */
    public void setLoad(LoadType value) {
        this.load = value;
    }

    /**
     * Gets the value of the fileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FileInfoType }
     *     
     */
    public FileInfoType getFileInfo() {
        return fileInfo;
    }

    /**
     * Sets the value of the fileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileInfoType }
     *     
     */
    public void setFileInfo(FileInfoType value) {
        this.fileInfo = value;
    }

    /**
     * Gets the value of the productFilter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterType }
     *     
     */
    public FilterType getProductFilter() {
        return productFilter;
    }

    /**
     * Sets the value of the productFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterType }
     *     
     */
    public void setProductFilter(FilterType value) {
        this.productFilter = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesType }
     *     
     */
    public ReferencesType getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesType }
     *     
     */
    public void setReferences(ReferencesType value) {
        this.references = value;
    }

    /**
     * Gets the value of the registry property.
     * 
     * @return
     *     possible object is
     *     {@link RegistryType }
     *     
     */
    public RegistryType getRegistry() {
        return registry;
    }

    /**
     * Sets the value of the registry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistryType }
     *     
     */
    public void setRegistry(RegistryType value) {
        this.registry = value;
    }

    /**
     * Gets the value of the xpathMaps property.
     * 
     * @return
     *     possible object is
     *     {@link XpathMapsType }
     *     
     */
    public XpathMapsType getXpathMaps() {
        return xpathMaps;
    }

    /**
     * Sets the value of the xpathMaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link XpathMapsType }
     *     
     */
    public void setXpathMaps(XpathMapsType value) {
        this.xpathMaps = value;
    }

    /**
     * Gets the value of the compiled property.
     * 
     * @return
     *     possible object is
     *     {@link CompiledType }
     *     
     */
    public CompiledType getCompiled() {
        return compiled;
    }

    /**
     * Sets the value of the compiled property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompiledType }
     *     
     */
    public void setCompiled(CompiledType value) {
        this.compiled = value;
    }

}
