//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.14 at 10:43:09 PM UTC 
//


package gov.nasa.pds.harvest.cfg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         DEV notes:
 * 
 *         Had to bury this one deeper because cannot have a choice in an all.
 *       
 * 
 * <p>Java class for load_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="load_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="bundles" type="{}bundles_type"/&gt;
 *         &lt;element name="directories" type="{}dirs_type"/&gt;
 *         &lt;element name="files" type="{}files_type"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "load_type", propOrder = {
    "bundles",
    "directories",
    "files"
})
public class LoadType {

    protected BundlesType bundles;
    protected DirsType directories;
    protected FilesType files;

    /**
     * Gets the value of the bundles property.
     * 
     * @return
     *     possible object is
     *     {@link BundlesType }
     *     
     */
    public BundlesType getBundles() {
        return bundles;
    }

    /**
     * Sets the value of the bundles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundlesType }
     *     
     */
    public void setBundles(BundlesType value) {
        this.bundles = value;
    }

    /**
     * Gets the value of the directories property.
     * 
     * @return
     *     possible object is
     *     {@link DirsType }
     *     
     */
    public DirsType getDirectories() {
        return directories;
    }

    /**
     * Sets the value of the directories property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirsType }
     *     
     */
    public void setDirectories(DirsType value) {
        this.directories = value;
    }

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link FilesType }
     *     
     */
    public FilesType getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilesType }
     *     
     */
    public void setFiles(FilesType value) {
        this.files = value;
    }

}
