//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nasa.pds.harvest.cfg;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for node_name_enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="node_name_enum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     <enumeration value="PDS_ATM"/>
 *     <enumeration value="PDS_ENG"/>
 *     <enumeration value="PDS_GEO"/>
 *     <enumeration value="PDS_IMG"/>
 *     <enumeration value="PDS_NAIF"/>
 *     <enumeration value="PDS_PPI"/>
 *     <enumeration value="PDS_RMS"/>
 *     <enumeration value="PDS_SBN"/>
 *     <enumeration value="PSA"/>
 *     <enumeration value="JAXA"/>
 *     <enumeration value="ROSCOSMOS"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "node_name_enum")
@XmlEnum
public enum NodeNameEnum {


    /**
     * 
     *             Planetary Data System: Atmospheres Node"
     *           
     * 
     */
    PDS_ATM,

    /**
     * 
     *             Planetary Data System: Engineering Node
     *           
     * 
     */
    PDS_ENG,

    /**
     * 
     *             Planetary Data System: Geosciences Node
     *           
     * 
     */
    PDS_GEO,

    /**
     * 
     *             Planetary Data System: Imaging Node
     *           
     * 
     */
    PDS_IMG,

    /**
     * 
     *             Planetary Data System: NAIF Node
     *           
     * 
     */
    PDS_NAIF,

    /**
     * 
     *             Planetary Data System: Planetary Plasma Interactions Node
     *           
     * 
     */
    PDS_PPI,

    /**
     * 
     *             Planetary Data System: Rings Node
     *           
     * 
     */
    PDS_RMS,

    /**
     * 
     *             Planetary Data System: Small Bodies Node
     *           
     * 
     */
    PDS_SBN,

    /**
     * 
     *             Planetary Science Archive
     *           
     * 
     */
    PSA,

    /**
     * 
     *             Japan Aerospace Exploration Agency
     *           
     * 
     */
    JAXA,

    /**
     * 
     *             Russian State Corporation for Space Activities
     *           
     * 
     */
    ROSCOSMOS;

    public String value() {
        return name();
    }

    public static NodeNameEnum fromValue(String v) {
        return valueOf(v);
    }

}
